[package]
name = "rutebot"
version = "0.1.0"
authors = ["Ilya Titkov <ilya@titkov.me>"]
edition = "2018"
keywords = ["telegram", "bot", "telegram-api", "telegram-bot"]
license = "MIT"
description = "Telegram bot api library"
categories = ["api-bindings"]
readme = "README.md"


[dependencies]
hyper = "0.12"
futures = "0.1"
serde = { version = "1.0", features = ["derive"] }
