fn_args_layout = "Tall"
fn_single_line = false
format_strings = true
format_macro_matchers = true

merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true

blank_lines_upper_bound = 2
max_width = 140

match_block_trailing_comma = true
